// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGf4j9U6tlVVO50jmfSM2OCOqTl3eIFXE',
    appId: '1:952374979589:web:0fbbea818a10b41227806c',
    messagingSenderId: '952374979589',
    projectId: 'twitterclone-b7ae1',
    authDomain: 'twitterclone-b7ae1.firebaseapp.com',
    storageBucket: 'twitterclone-b7ae1.firebasestorage.app',
    measurementId: 'G-J8CGWL7WSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO74znMotLdpcn7Kr_H-AT6q58L08ghlw',
    appId: '1:952374979589:android:a20b3ab98e169c5827806c',
    messagingSenderId: '952374979589',
    projectId: 'twitterclone-b7ae1',
    storageBucket: 'twitterclone-b7ae1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9E0Nwoy4WLjR6PtEuvE24l7rvOwttvJY',
    appId: '1:952374979589:ios:4798d74d91c669a527806c',
    messagingSenderId: '952374979589',
    projectId: 'twitterclone-b7ae1',
    storageBucket: 'twitterclone-b7ae1.firebasestorage.app',
    iosBundleId: 'com.example.twitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9E0Nwoy4WLjR6PtEuvE24l7rvOwttvJY',
    appId: '1:952374979589:ios:4798d74d91c669a527806c',
    messagingSenderId: '952374979589',
    projectId: 'twitterclone-b7ae1',
    storageBucket: 'twitterclone-b7ae1.firebasestorage.app',
    iosBundleId: 'com.example.twitterClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGf4j9U6tlVVO50jmfSM2OCOqTl3eIFXE',
    appId: '1:952374979589:web:9148a8a80ac6ab2227806c',
    messagingSenderId: '952374979589',
    projectId: 'twitterclone-b7ae1',
    authDomain: 'twitterclone-b7ae1.firebaseapp.com',
    storageBucket: 'twitterclone-b7ae1.firebasestorage.app',
    measurementId: 'G-5KE51QG6VZ',
  );
}
